// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Sun Nov 26 15:57:20 2023

PWM_up PWM_up_inst
(
	.clk_200M(clk_200M_sig) ,	// input  clk_200M_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.CCR(CCR_sig) ,	// input [15:0] CCR_sig
	.pwmout1(pwmout1_sig) ,	// output  pwmout1_sig
	.pwmout1N(pwmout1N_sig) 	// output  pwmout1N_sig
);

defparam PWM_up_inst.ARR = 'b1111111111111111;
defparam PWM_up_inst.DEADTIME = 'b0000000000010100;
